config/routes.rb
Rails.application.routes.draw do
  root to: 'inquiries#new'

  resources :inquiries
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/inquiry.rb
class Inquiry < ApplicationRecord
  has_many_attached :images
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def authenticate
    return if Rails.env == "test"
    authenticate_or_request_with_http_basic do |username, password|
      pw = Rails.application.credentials.basis_auth_password
      if (username == 'kanri' && password == pw)
        session[:user] = username
      end
    end
  end
end

app/controllers/inquiries_controller.rb
class InquiriesController < ApplicationController
  before_action :set_inquiry, only: [:show, :edit, :update, :destroy]
  before_action :authenticate, except: [:show, :new, :create]

  # GET /inquiries
  def index
    @inquiries = Inquiry.all
  end

  # GET /inquiries/1
  def show
  end

  # GET /inquiries/new
  def new
    @inquiry = Inquiry.new
  end

  # GET /inquiries/1/edit
  def edit
  end

  # POST /inquiries
  # POST /inquiries.json
  def create
    @inquiry = Inquiry.new(inquiry_params)

    if @inquiry.save
      NotificationsMailer.sent.deliver_later
      NotificationsMailer.received.deliver_later
      redirect_to @inquiry, notice: 'Inquiry was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /inquiries/1
  def update
    if @inquiry.update(inquiry_params)
      redirect_to @inquiry, notice: 'Inquiry was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /inquiries/1
  def destroy
    @inquiry.destroy
    redirect_to inquiries_url, notice: 'Inquiry was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_inquiry
      @inquiry = Inquiry.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def inquiry_params
      params.require(:inquiry).permit(:name, :email, :purpose, :body, images:[])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/inquiries_helper.rb
module InquiriesHelper
end

app/views/inquiries/_form.html.erb
<%= form_with(model: inquiry) do |form| %>
  <% if inquiry.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(inquiry.errors.count, "error") %> prohibited this inquiry from being saved:</h2>

      <ul>
        <% inquiry.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :email %>
    <%= form.text_field :email, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :purpose %>
    <%= form.number_field :purpose, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :body %>
    <%= form.text_area :body, class: "form-control" %>
  </div>

  <div class="form-field">
    <%= form.label :images %>
    <%= form.file_field :images, multiple: true, class: "form-control" %>
  </div>

  <div class="actions">
    <%= form.submit nil, class: "btn btn-primary" %>
  </div>
<% end %>

app/views/inquiries/edit.html.erb
<h1>Editing Inquiry</h1>

<%= render 'form', inquiry: @inquiry %>

<%= link_to 'Show', @inquiry %> |
<%= link_to 'Back', inquiries_path %>

app/views/inquiries/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Inquiries</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Purpose</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @inquiries.each do |inquiry| %>
      <tr>
        <td><%= inquiry.name %></td>
        <td><%= inquiry.email %></td>
        <td><%= inquiry.purpose %></td>
        <td><%= inquiry.body %></td>
        <td><%= link_to 'Show', inquiry, class: "btn btn-light btn-sm" %></td>
        <td><%= link_to 'Edit', edit_inquiry_path(inquiry), class: "btn btn-light btn-sm" %></td>
        <td><%= link_to 'Destroy', inquiry, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger btn-sm" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Inquiry', new_inquiry_path, class: "btn btn-primary" %>

<br>

<% text = "<b>1</b>\n<i>2</i>\n3 >= a" %>
<%= text %>
<hr/>
<%= h(text) %>
<hr/>
<%= simple_format(text) %>
<hr/>
<%= strip_tags(text) %>
<hr/>
<%= sanitize(text) %>
<hr/>
<%= sanitize(text.gsub("\n", "<br>")) %>

app/views/inquiries/new.html.erb
<div class="row">
  <div class="offset-md-3 col-md-6">
    <h1>New Inquiry</h1>
      <%= render 'form', inquiry: @inquiry %>

      <% if session[:user] == "admin" %>
      <%= link_to 'Back', inquiries_path %>
      <% end %>
  </div>
</div>

app/views/inquiries/show.html.erb
<p id="notice"><%= notice %></p>

<% if session[:user] == 'kanri' %>
  <p>
    <strong>Name:</strong>
    <%= @inquiry.name %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= @inquiry.email %>
  </p>

  <p>
    <strong>Purpose:</strong>
    <%= @inquiry.purpose %>
  </p>

  <p>
    <strong>Body:</strong>
    <%= @inquiry.body %>
  </p>

  <% if @inquiry.images.attached? %>
    <p>
    <% @inquiry.images.each do |i| %>
      <%= image_tag i %>
    <% end %>
    </p>
  <% end %>

  <%= link_to 'Edit', edit_inquiry_path(@inquiry) %> |
  <%= link_to 'Back', inquiries_path %>
<% else %>
  <p>Thank you for the inquiry!</p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Railsapp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
  </head>

  <body>
    <% if notice %>
      <div id="notice" class="alert alert-success"><%= notice %></div>
    <% end %>
    <% if alert %>
      <div id="alert" class="alert alert-warning"><%= alert %></div>
    <% end %>
   <div class='container'>
      <%= yield %>
    </div>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
  </body>
</html>